// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const String webApiKey =
      String.fromEnvironment('FIREBASE_WEB_API_KEY');
  static const String androidApiKey =
      String.fromEnvironment('FIREBASE_ANDROID_API_KEY');
  static const String iosApiKey =
      String.fromEnvironment('FIREBASE_IOS_API_KEY');
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: webApiKey,
    appId: '1:842842326555:web:28d0133dc0d33201a55abe',
    messagingSenderId: '842842326555',
    projectId: 'share-your-route-ff4ad',
    authDomain: 'share-your-route-ff4ad.firebaseapp.com',
    databaseURL: 'https://share-your-route-ff4ad-default-rtdb.firebaseio.com',
    storageBucket: 'share-your-route-ff4ad.appspot.com',
    measurementId: 'G-WBFQSXCGQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: androidApiKey,
    appId: '1:842842326555:android:a595dda6de706dcba55abe',
    messagingSenderId: '842842326555',
    projectId: 'share-your-route-ff4ad',
    databaseURL: 'https://share-your-route-ff4ad-default-rtdb.firebaseio.com',
    storageBucket: 'share-your-route-ff4ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: iosApiKey,
    appId: '1:842842326555:ios:d718e23a77fc684aa55abe',
    messagingSenderId: '842842326555',
    projectId: 'share-your-route-ff4ad',
    databaseURL: 'https://share-your-route-ff4ad-default-rtdb.firebaseio.com',
    storageBucket: 'share-your-route-ff4ad.appspot.com',
    iosClientId:
        '842842326555-o7vd42851kko4r1bp7ieui7l0hbul142.apps.googleusercontent.com',
    iosBundleId: 'com.example.shareYourRouteFront',
  );
}
