name: Flutter

on:
  # Runs this action when you push on main
  push:
    branches: ["main"]
  # Runs this when a PR against main is created
  pull_request:
    branches: ["main"]

jobs:
  flutter_job:
    # The machine, we can also use windows-latest or ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      # Clones the project on the machine
      - uses: actions/checkout@v4
